### ISSUE TITLE
NO CONFIG

### ISSUE THREAD

**Issue by Maninarang** [spacedeck/spacedeck-open#1]
There is no config file in the code

**Comment by mntmn** [comment]
What do you mean? There is a config file here https://github.com/spacedeck/spacedeck-open/blob/master/config/default.json

**Comment by Maninarang** [comment]
Sorry for this silliest issue(which was not actually an issue)..

Can we make it work without S3 ??as i am working on windows.. i do have aws-instance..but want to test locally(the media part). can we achieve this without s3?

**Comment by mntmn** [comment]
Yes, there are several solutions for this. I will publish an "embedded" branch in a few minutes that doesn't use S3 and you can give it a try.

**Comment by Maninarang** [comment]
that would be great...looking forward

**Comment by mntmn** [comment]
OK, check out this branch: https://github.com/spacedeck/spacedeck-open/tree/embedded

In config/default.json you can now find a new option, this is where files are uploaded to:
`"storage_local_path": "./storage",`

Also, this branch doesn't require Redis anymore.

**Comment by Maninarang** [comment]
yes this storage is working. thanks man
