### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tillias** [spacedeck/spacedeck-open#102]
Hello folks, thanks a lot for making this awesome piece of software available under OSS. One thing is not clear to me, it is available under GPLv3, so we can use it only in non-profit, non-commercial organizations only? Or is it also legal to use it for commercial purposes?
Please advise

**Comment by mntmn** [comment]
The license is AGPL-3.0. Please inform yourself about the legal consequences of open source software licenses.

In short, you can sell software or SaaS based on Spacedeck _but_ you have to open-source your software/the changes under AGPL as well.

**Comment by tillias** [comment]
Well, the idea was to simply use it, not develop some software based on the source code of it. I'm pretty familiar with GPL based licenses if it is about extending using it on a source code level, but not really sure how it works if I simply want to build and deploy it without any modification.

**Comment by mntmn** [comment]
No problem to just use it then!
