### ISSUE TITLE
Remove authentication

### ISSUE THREAD

**Issue by konnect1989** [spacedeck/spacedeck-open#103]
Hi
can anyone help with removing authentication from spacedeck, customize it to automatically create a whiteboard with meeting_id  so it can be used with Jitsi as whiteboard?

**Comment by zeigerpuppy** [comment]
That's a good idea.  It would also help with integrating spacedeck with [sandstorm](https://docs.sandstorm.io/en/latest/developing/) (as no auth is needed)

**Comment by mntmn** [comment]
This is already implemented, see the wordpress plugin example. You just need to set up an api_key in the config: https://github.com/spacedeck/spacedeck-open/blob/mnt/integrations/wordpress/plugins/spacedeck/spacedeck.php

**Comment by rasos** [comment]
@zeigerpuppy any plans to offer spacedeck as a sandstorm app?

**Comment by de-johannes** [comment]
@konnect1989 were you able to realize it. jitsi meet <-> spacedeck-open.
can you help me with it? i do not what to do with these informartion above.
