### ISSUE TITLE
Production env doesn't start

### ISSUE THREAD

**Issue by nicksellen** [spacedeck/spacedeck-open#109]
I'm having some issues, and noticed I was running in development mode, but when I set `NODE_ENV=production` then I get:

```
Error: ENOENT: no such file or directory, stat '/path/to/spacedeck/build/assets/images/favicon.png'
```

... which makes sense, as there is no `build/` directory in the repo, and I can't see any build command.

I see here is where production mode refers to `build/` dir: https://github.com/spacedeck/spacedeck-open/blob/7c6d5c83db6b89042f81ad10a5c882b7c1459ea0/spacedeck.js#L45-L47

What is the intention here?

(the reason I was looking at this is I'm experiencing some issues where the client is sending loads of PUT requests that get backlogged, and everything becomes unresponsive, and wondering if running in development mode was implicated...).

**Comment by mntmn** [comment]
The production mode will not help with this, actually it wouldn't change anything that I know of.
