### ISSUE TITLE
Is there any way to move the canvas?

### ISSUE THREAD

**Issue by introlinux** [spacedeck/spacedeck-open#114]
Is there any way to move the canvas quickly with the mouse? Is there a keyboard shortcut or something like that? Moving around the canvas with the scroll bars is a hard work when you have to continually go from one place to another.

**Comment by mntmn** [comment]
Yes, for example:
- Drag with middle mouse button
- Hold spacebar and drag with left mouse button (like in Adobe products)

**Comment by introlinux** [comment]
Cool! :+1: 

Thanks.
