### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by gregtampa** [spacedeck/spacedeck-open#124]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
root@hackbama:~/spacedeck-open# node spacedeck.js
/root/spacedeck-open/models/db.js:213
  init: async function() {
              ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/spacedeck-open/spacedeck.js:3:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by juliandavidmr** [comment]
What node version do you have?

I recommend at least v12.18.4.

**Comment by gregtampa** [comment]
will try now thanks.
this is output of the commands i ran to upgrade for others
`root@hackbama:~# nodejs -v
v4.2.6
root@hackbama:~# sudo npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.
root@hackbama:~# sudo npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/lib
└── n@6.7.0

root@hackbama:~# sudo n stable

  installing : node-v14.15.0
       mkdir : /usr/local/n/versions/node/14.15.0
       fetch : https://nodejs.org/dist/v14.15.0/node-v14.15.0-linux-x64.tar.xz
   installed : v14.15.0 (with npm 6.14.8)

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"
`

**Comment by gregtampa** [comment]
SOLVED-----
had to do 
PATH="$PATH"
or restart the shell...
then it worked!
