### ISSUE TITLE
Line/arrows are missing in thumbnails and PDF export

### ISSUE THREAD

**Issue by nblock** [spacedeck/spacedeck-open#141]
## Expected Behavior
All elements are visible in thumbnails and PDF export.

## Actual Behavior
It seems that only block elements such as text boxes are part of thumbnails and PDF exports. For example, a simple drawing with a single text box and some arrows only contains the text box. All arrows are missing. Affects thumbnails and PDF exports.

## Steps to Reproduce the Problem

  1. Get current version
  2. New diagram with text box and some arrows
  3. navigate to spaces or generate a PDF export

## Specifications

  - OS Platform and Distribution: Debian 10 (Buster)
  - spacedeck-open: 16e926b76abaa905197d7a3269ea5b79dc9fa1a1
  - Node version: v10.21.0
  - Database engine: sqlite

**Comment by Whitie** [comment]
Any progress here? This is really a showstopper.
Platform here is Arch Linux and Ubuntu 18.04 LTS.

**Comment by comsyspro** [comment]
I also want to know how you can fix this issue. When I export a room as pdf, then the scribble and arrow lines are not rendered in the output pdf. Any ideas which part of code causes this problem?

**Comment by nblock** [comment]
Just tried the latest available commit - ff403a9c2364fc94a98029f6c0096f38e5d07fae - PDF export now and thumbnail generation work now.
