### ISSUE TITLE
No way to edit text field with mobile device (Safari mobile, iPadOS 14)

### ISSUE THREAD

**Issue by tim-krieger** [spacedeck/spacedeck-open#147]
## Expected Behavior
A text field has to be editable.

## Actual Behavior
I can't edit the text field.

## Steps to Reproduce the Problem

  1. Create text field
  2. Select text field, tip several time on »Text«

## Specifications

  - iPadOS 14, Safari mobile

**Comment by mntmn** [comment]
I added a new "Edit Text" button to alleviate this in this PR:
https://github.com/spacedeck/spacedeck-open/pull/152

Can you give it a try?

**Comment by tim-krieger** [comment]
Thanks! It works.

**Comment by tim-krieger** [comment]
Probably related: I can't insert text in a graphic with my touch device.

**Comment by jolly-jump** [comment]
Seems to work for us as well
