### ISSUE TITLE
Media upload is not working with Safari mobile (iPadOS 14)

### ISSUE THREAD

**Issue by tim-krieger** [spacedeck/spacedeck-open#149]
## Expected Behavior
Media upload is working.

## Actual Behavior
I can't upload images. Haven't tried video and audio files yet.

## Steps to Reproduce the Problem

  1. Tip on the upload icon (I have to tip twice) and open the file manager
  2. All files are greyed out. I can't select a file.

## Specifications

  - Safai mobile, iPadOS 14

**Comment by mntmn** [comment]
I don't have an iPad new enough to run that OS, and I also don't have a current Mac. I do have an iPhone and when I try it there, the "Media" button just doesn't do anything.

**Comment by mntmn** [comment]
Probably fixed, see https://github.com/spacedeck/spacedeck-open/pull/152

**Comment by tim-krieger** [comment]
Works like expected! Thanks a lot for your help.
