### ISSUE TITLE
Access via public ip not possible

### ISSUE THREAD

**Issue by senycorp** [spacedeck/spacedeck-open#18]
Hi,

i am running spacedeck on a vm an try to access it via its public ip. Unfortunately the initial request returns a 404 and shows a "Page not found" site. I try to set some configuration parameters in config/default and spacedeck.html but nothing worked.

We would like to run it in development mode to profit from nodemon.

**Comment by mntmn** [comment]
Hi, thanks for reporting this. I just pushed a fix that should take care of that. Can you pull and try again please?

**Comment by mntmn** [comment]
Fixed and closed due to inactivity.
