### ISSUE TITLE
Problem Sending Mail via SSL

### ISSUE THREAD

**Issue by Lukeva** [spacedeck/spacedeck-open#195]
## Expected Behavior
Password reset mails get send.

## Actual Behavior
Error "Error sending email: { [Error: 140439642179392:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:"

## Possible Solution
Unfortunately I have no Idea. I have tried using my Mail Server with Hetzner mail.your-server.de as well as Google SMTP Relay smtp-relay.gmail.com both give the same error when trying to send password reset mails. I am thankful for any Ideas!

## Specifications
  - OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
  - Node version: 10.24
  - Database engine (e.g., SQLite): SQLite

**Comment by rds13** [comment]
Can you add your configuration file with password removed so it can be look at ?

**Comment by Lukeva** [comment]
Sure! Here is the complete file - I tried all possibilities with "secure" and "require tls" option, but didn´t get lucky so far.

"team_name": "Spacedeck XXX",
  "contact_email": "XXX@XXX.org",

  "host": "::",
  "port": 9666,
  "endpoint": "https://XXX.XXX.org",
  "invite_code": "XXX",

  "storage_dialect": "sqlite",

  "storage_host": "localhost",
  "storage_database": "spacedeck",
  "storage_username": "username",
  "storage_password": "password",

  "storage_local_path": "./storage",
  "storage_local_db": "./database.sqlite",
  "storage_bucket": "spacedeck",
  "storage_cdn": "/storage",
  "storage_endpoint": "https://XXX.XXX.org",

  "mongodb_host": "localhost",
  "redis_mock": true,
  "redis_host": "localhost",

  "export_api_secret": "XXX",

  "mail_provider": "smtp",
  "mail_smtp_host": "mail.your-server.de",
  "mail_smtp_port": 587,
  "mail_smtp_secure": true,
  "mail_smtp_require_tls": false,
  "mail_smtp_user": "deck@netzwerk-n.org",
  "mail_smtp_pass": "XXX",

**Comment by rds13** [comment]
This looks like issue #38 where server port was not configured to handle tls. Can you check that the smtp host handle tls on port 587 ?
You can use this command for example :
````
     openssl s_client -connect mail.your-server.de:587
````

**Comment by Lukeva** [comment]
@rds13 Thank you so much for your help! I did mix up SSL and TLS Ports. Checking with the command you suggested, I found out that my Mailserver (as well as the G-Mail SMTP-Relay) don´t support TLS on Port 587 but do on Port 465. However when trying around before I also forgot to rebuild the docker image, and thus didn´t see any changes. I got it working now. Thank you very much!
