### ISSUE TITLE
Uploading Media

### ISSUE THREAD

**Issue by Maninarang** [spacedeck/spacedeck-open#2]
i am facing following issue while uploading media

![issue](https://user-images.githubusercontent.com/15976897/34664196-b4e81396-f480-11e7-8b99-90f1f1eec6bc.png)

**Comment by mntmn** [comment]
Ah, this is because you don't have the "file" tool on your system: http://man7.org/linux/man-pages/man1/file.1.html

On Windows, you might get this from Cygwin or MinGW.

**Comment by Maninarang** [comment]
Hi,
As you sugested i installed the Cygwin and its packages..but still no luck..facing same issue(above) and for the pdf part i am receiving empty response and 400 alert

**Comment by Maninarang** [comment]
ok i  did this on ubuntu and its working.. thanks
