### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Photon89** [spacedeck/spacedeck-open#219]
## Expected Behavior

Installation succeeds.

## Actual Behavior

Installation fails. Here is the log output: https://pastebin.com/YRz0nxBF

## Possible Solution

I'm somewhat overwhelmed by the massive error output...

## Steps to Reproduce the Problem

  1. git clone the spacedeck repository
  2. run npm install
  3. observe the error output

## Specifications

  - OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro Linux, fully updated
  - Node version: 16.6.1
  - Database engine (e.g., SQLite): SQLite 3.36.0

**Comment by rds13** [comment]
Hy,
Sorry to hear that you have problems installing spacedeck on your side.
I'm not familiar with Manjaro but it seems you might be running on an ARM proccessor. Can you confirm ?

**Comment by Photon89** [comment]
@rds13 Thanks for your reply! No, it's a Thinkpad L13 Yoga with in i5 CPU which I am using for the first test, though I actually intended to run it on a RasPi later.

**Comment by Zerotonine** [comment]
@Photon89 your Node version is to high, try using a lower version.
I run into the same errors on Manjaro, but with node v10.24.1 spacedeck now works (with nvm you are able to install multiple node versions simultaneously)

**Comment by pixelass** [comment]
1. Active LTS for node is v14 https://nodejs.org/en/about/releases/
2. Versions below 16 have issues on Apple Silicon (are not supported) https://github.com/nodejs/build/issues/2474

I think it's worth investing some time to add support for Node v16.

**Comment by mntmn** [comment]
Fixed, now works with node 18.
