### ISSUE TITLE
Scribble Mouseup

### ISSUE THREAD

**Issue by James9074** [spacedeck/spacedeck-open#22]
This tool is amazing, minus one very important thing: Scribble is almost useless if you can't perform multiple scribbles within one scribble object.

Example: If I click my mouse down, draw a linne, and release the mouse, I have to create a whole new scribble object just to create a new line that intersects the first one. 

What purpose is scriblle supposed to serve? I'd assume it fills the gap as a whiteboard-esque quick drawing feature, but that's not quite the case here.

**Comment by mntmn** [comment]
Thanks, how would you propose to solve it?

**Comment by mntmn** [comment]
Closed due to inactivity
