### ISSUE TITLE
Add support for Node.js v16

### ISSUE THREAD

**Issue by pixelass** [spacedeck/spacedeck-open#243]
## Expected Behavior
Current Node versions (LTS) should be supported

1. Active LTS for node is v14 https://nodejs.org/en/about/releases/
2. Versions below 16 have issues on Apple Silicon (are not supported) https://github.com/nodejs/build/issues/2474

I think it's worth investing some time to add support for Node v16.

## Actual Behavior
Seems to only work with Node v10

## Possible Solution
Using outdated (unsafe) legacy versions

## Steps to Reproduce the Problem

  1. See https://github.com/spacedeck/spacedeck-open/issues/219
  2. See https://github.com/spacedeck/spacedeck-open/issues/234

## Specifications

  Irrelevant

**Comment by mntmn** [comment]
Fixed, now works with node 18.
