### ISSUE TITLE
First test with Spacedeck

### ISSUE THREAD

**Issue by Tamzejian** [spacedeck/spacedeck-open#25]
Hello,
I used to use Spacedeck for educational purposes (musical education). I am not a professional programmer (I know basics and can tweak one thing or two).
For a start, trying to create a local web site on my computer that can integrate animated files, videos, MIDI, etc and I used Spacedeck.
Interactive environment is interesting also, but one problem at a time.

I used electron to launch Spacedeck, it works for audio files, doesn't play immediately (must reload).
However, cannot "upload" pdf (either methods) files or videos (tried mp4 format and failed). I tried with the storage dependencies but don't know how to install them (I use windows 10 and ubuntu studio).

I also tried to load Spacedeck to my web browser (localhost) but failed also (node spacedeck.js, missing packages, asking to install sqlite3 manually).

I can search tutorials for the simple issues, but need advice.

My students and I thank you.
Sincerely.

**Comment by mntmn** [comment]
Hi, thanks for trying it out. Can you give a few more details about the errors that you encounter? For example, whenever you try something and encounter error messages, make a screenshot and post it here. That way I can try to give suggestions.
