### ISSUE TITLE
Sharing of folders

### ISSUE THREAD

**Issue by Schrigga** [spacedeck/spacedeck-open#26]
When I ran node spacedeck.js and register two users I'm not able to share a folder between these users. 
On the command line I see the emails which should be sent. Currently they won't be sent. Where can I configure how to sent the emails?
If I click on the link printed there, nothing happens.

**Comment by mntmn** [comment]
This is now fixed in master thanks to https://github.com/spacedeck/spacedeck-open/commit/ea4f40b628e5c47b1fa64e2fb0b90fa8a97dd6a0

You have to configure your email server in config/default.json.
