### ISSUE TITLE
Chrome issues: Wrong event listener binding 

### ISSUE THREAD

**Issue by senycorp** [spacedeck/spacedeck-open#32]
Hey guys,

We found a bug that causes that several elementary listeners are bound to touch events on non touch devices. This is because the browser will always offer touch events despite of the device type. The result is that spacedeck does not react on anything. Please check your code in spacedeck_whiteboard.js. The part which is responsible for detecting touch devices and registering the event listeners should be updated. It is better to register events for touch and non touch devices always because of hybrid devices. Your touch detection routine seems to be outdated too.

Thanks for this nice piece of code

**Comment by sfakir** [comment]
@senycorp  Did you fix this? is it possible to create a pull request?

**Comment by senycorp** [comment]
@sfakir yes, I fixed this issue in a repo which has some more new features. I can create a patch for you but can not guarantee if it is apply able without any problems. Pull request is not possible because the repo is located in an private bitbucket repository.

**Comment by sfakir** [comment]
I also fixed a couple of things, are you going to use this in production? Are you inteeessted in sharing progress?

**Comment by senycorp** [comment]
The project i was a part of is now maintained by other developers. In
consideration of the commit history I can say that they are not really
focused in bringing spacedeck to the next level. It is only used for
primitive task. The only thing I did was writing a connector for
iconfinder. This feature offers the possibility to search for icons by
keyword and add them to the board. Several Bugfixes I cannot remember
today. I can share this with you if you are interested. Further tasks will
be done by the actual Project team. If you wish I can contact them. That's
all I can do for you 😊.

Simon Fakir <notifications@github.com> schrieb am Mi., 7. Nov. 2018, 01:01:

**Comment by mntmn** [comment]
Fixed in 8e11b6c4faffd2b95447d67c3f8736e34b748126.
