### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by sfakir** [spacedeck/spacedeck-open#33]
Dear developers,
thank you for sharing the source code. The look and feel is really awesome.

However, your production deployment requires js/... minified in the dist folder minifing the js. What deployment pipeline do you use here?

thank you

Simon

**Comment by mntmn** [comment]
I would suggest that minification is not necessary anymore nowadays. Production mode should just deliver the same JS as development mode.

**Comment by webdevisme** [comment]
I disagree. Production mode is production mode for a reason :)
Why do you need unminified code in the production version?

**Comment by mntmn** [comment]
OK, why do you need minified code if you have gzip and http/2? This just adds build and tooling complexity for not much gain. The Spacedeck JS code is just a few kilobytes. And if unminified, it’s very easy to debug/inspect problems in production, too.

**Comment by webdevisme** [comment]
Hmmm... good point. 
And it wouldn't be difficult for someone who really needs minification for production to branch off and add it themselves.
