### ISSUE TITLE
Download Space as Zip

### ISSUE THREAD

**Issue by Nina-ed** [spacedeck/spacedeck-open#34]
Dear developers,
I bring forward and make a separate issue from previous  [#29](https://github.com/spacedeck/spacedeck-open/issues/29). As noted I've tried to pinpoint and fix some issues I reported but not being a developer per se have not been able to progress any further. The main issue I believe, and one that seems to have been an impetus for making Spacedeck "open", is the ability to import saved spaces but also equally important to save spaces for reuse in educational settings. 

Is the issue with saving spaces (receiving "ZIP export problem 500)" simply a path, permission, missing module issue or requires code fixes? 

Appreciate any pointers or a possible fix for this or any other issues I reported previously.

**Comment by mntmn** [comment]
Sorry, this functionality is currently put on hold and might be implemented again later.

**Comment by hex-m** [comment]
A way to export/import Spaces would be highly appreciated. This would make users less dependent on a server operator as they could keep their own copies of their work. Could you please re-open this issue to track this or should I create a new feature request for it?
