### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Rohanmalodia** [spacedeck/spacedeck-open#35]
Below are some features I need to implement.
1)     When I create pdf it only takes shapes and images in pdf, scribbled drawing or arrows are not shown in pdf.
2)	Is it possible to show the freehand drawing in real-time to other users? Current behavior – drawings get rendered on another side on the mouse click release. We want this to be in real-time, with the drag of the mouse.
3)	Eraser tool – can we implement an eraser/rubber tool to rub a portion of freehand drawing?
4)	Multiple boards- right now we can add multiple spaces and in a space, there’s only one whiteboard. So can we implement it in such a way that user can add multiple whiteboards as per it’s needed in a single space? Similar to adding new sheet tabs on Google Sheet.
5)	Text highlighter.
6)	Rotation of shapes that are placed on the board.

Thanks in advance

**Comment by webdevisme** [comment]
Hi, I think that you need to employ some developers to implement the features you require. The updates to space-deck open have stopped over the last few years, and, whilst a great tool, it's not something that people seem to be willing to work on for free. The fact that is even available for free is great in itself!

It shouldn't be difficult to find some competent Vue devs to help with the features you require.
