### ISSUE TITLE
On trying to share a space: SQLITE_ERROR: no such column: membership.space

### ISSUE THREAD

**Issue by bernhardreiter** [spacedeck/spacedeck-open#39]
When trying to share a link, when using the link from a different browser, it does not work.
Error message on the log:

```
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: membership.space
```

Any ideas?

(This is on Debian Buster with nodejs 10.15.2~dfsg-2.)

**Comment by webdevisme** [comment]
Does logging into spacedeck in the different browser first make a difference?

**Comment by mntmn** [comment]
Hi, thanks for reporting. This is now fixed in 01a6bec80e3f214697be3f5edd37930a4f8a0312.

Can you try it?

**Comment by bernhardreiter** [comment]
@mntmn thanks for the patch. Just tried the new version in the mnt branch, where you did the changes on the old code. Migration ran fine according to log message, but trying to log in failed because of `Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: email_invited`. :)  As the database probably is migrated now, I'll have to apply the patch to the old version or freshly restart everything later today.

**Comment by bernhardreiter** [comment]
Works on branch `mnt`. (After moving database.sqlite out of the way and see the config about how to register , then restarting.). Thanks!
