### ISSUE TITLE
Not able to upload media on Windows Server

### ISSUE THREAD

**Issue by leeredimpressions** [spacedeck/spacedeck-open#40]
Everything else works perfectly fine. Just when I upload an image (or drag n drop in an image), the loading placeholder keeps spinning.  There's nothing put into the "storage" folder except the empty my_spacedeck_bucket folder. 

The upload works completely fine using the compiled version. Same Windows server. 

Any idea?

**Comment by mntmn** [comment]
Which branch are you using? "mnt"?

Did you install graphicsmagick?

**Comment by huzaifahj** [comment]
I'm getting the same error, just on images. All other file uploads work fine. `npm install` installed graphicsmagick but I tried updating it too.

[https://imgur.com/a/CNzUqQX](Screenshot) of 400 Error

**Comment by mntmn** [comment]
Can you try installing graphicsmagick system-wide? I guess it's something about the PATH. It needs to be able to find the "gm" executable (probably "gm.exe" on Windows). I'm not very familiar with Windows, though, sorry.

**Comment by huzaifahj** [comment]
I'm actually using Linux (Ubuntu 18.04), is there an equivalent? Thanks

**Comment by mntmn** [comment]
`sudo apt install graphicsmagick`

**Comment by huzaifahj** [comment]
That fixed it! Maybe add it to the "optional dependencies", as I thought the GM node module would be enough. Thanks
