### ISSUE TITLE
How to use application without login or sign up?

### ISSUE THREAD

**Issue by SriramScorp** [spacedeck/spacedeck-open#41]
Is the application only for people who owned a subscription at spacedeck.com?

**Comment by mntmn** [comment]
I don't understand. What did you try to do?

**Comment by SriramScorp** [comment]
Following the instructions in the readme file, I installed nodejs v10, cloned the repo, ran npm install and then started the web server (spacedeck.js). The default landing page of the application prompts for either login or sign up. Signing up requires an invite code.

**Comment by mntmn** [comment]
The invite code is in config/default.json.

**Comment by SriramScorp** [comment]
Okay. Is every user required to sign up using the same invite code? I was hoping, being a self hosted version and all, the app will work out of box.

**Comment by mntmn** [comment]
Try setting the invite code to “” (empty string) in the config. I guess then you should be able to create accounts leaving the invite code field blank.

You don’t necessarily need multiple user accounts: if you click on Share in a space, you get a link for anonymous users to collaborate in that space.

**Comment by SriramScorp** [comment]
Okay. I'll give it a try. Btw, is there no way to bypass the sign up? I was considering using it as a collaborative whiteboard, similar to etherdraw.

**Comment by mntmn** [comment]
Just read the second paragraph of my last answer again.

**Comment by SriramScorp** [comment]
I did. What I infer is that, for anyone to be able to CREATE a space, they need to create an account. Once a space had been created, anyone with link to the space can collaborate in that space. Correct me if I'm wrong.

**Comment by mntmn** [comment]
Ah, now I understand. Correct. This is not possible without an account. As a workaround, you could just create one account and give everybody the credentials.

**Comment by SriramScorp** [comment]
Okay. Thanks for the clarification. It would be nice if we could make authentication optional and use the application in the same way as, say, etherpad. Please consider such a feature.

**Comment by mntmn** [comment]
If many people request this feature I might consider it, but not now. Until then you can work around it by creating a user and then pre-fill the `user_forms_email: ""` and `login_password: ""` in `public/javascripts/spacedeck_users.js`.

**Comment by ashirwad007786** [comment]
@magegu I would like if there is option in config where we can bypass the login and create room directly,

**Comment by hex-m** [comment]
> If many people request this feature I might consider it, but not now.

I created a new issue that people can upvote. https://github.com/spacedeck/spacedeck-open/issues/199
