### ISSUE TITLE
Keep current tool while editing space

### ISSUE THREAD

**Issue by lol7344** [spacedeck/spacedeck-open#42]
Similar issue to #22 .
Spacedeck is the **best** collaborative self-hosted solution I could find in more than a week of daily research.
However, the "Scribble" tool is almost useless since to draw every single line you have to select the tool again from the toolbar, every time.

A solution I suggest is to just leave the tool "active" until told otherwise: when I click on "Scribble", I should be able to draw as many lines as I want. Then, when I'm done drawing lines, I can just click again on the "Scribble" tool to disable it.

This could very well be applied to all tools, however I think "Scribble" is the most used one and would be affected positively the most.

**Comment by huzaifahj** [comment]
I agree! Really appreciate the team for making this project open source. It's one of the most refined whiteboards out there, but unfortunately the way Scribble works is a really big disadvantage and key for whiteboards

**Comment by lol7344** [comment]
@huzaifahj I have found an easy way to keep Scribble/Arrow enabled until you move the cursor out of the screen (doesn't work on mobile tho).

you can see it in my fork: https://github.com/lol7344/spacedeck-open/commit/7c5fd6485eb552271421eb9e6be9a08873500db2

you just have to edit file "public/javascripts/spacedeck_whiteboard.js" and remove line 738 `"scope.active_tool = "pointer";"`

**Comment by huzaifahj** [comment]
Quite a good solution! I'm new to github but maybe you can make a pull request?

**Comment by lol7344** [comment]
Yeah sure I could, although I don't think a single line edit is worth a pull request 🤣 
And also, this causes a bug on mobile devices (although the whole project isn't really mobile-friendly). If you select a tool on a mobile device, you won't be able to deselect it unless you reload the page. This is because my edit was not a feature, but just a quick fix.
A proper way to do this would be to also add a check, in case you clicked "Scribble" again while having it already selected -> deselecting it. This would be a really easy feature to implement by one of the devs, it's just a question of copy-pasting the select feature and making it deselect instead.
I'd be happy to do it but I'm kinda busy at the moment, and I had to move from spacedeck to another project since I needed mobile usability.
I will gladly try adding this in my fork (and then consider making a pull request) as soon as I'm free, however I already know I'll probably forget :(

**Comment by huzaifahj** [comment]
I understand! Hopefully it gets the attention of one of the Devs. Can I ask what other project you moved to?

**Comment by lol7344** [comment]
Yeah sure :) I forked https://github.com/cracker0dks/whiteboard in https://github.com/lol7344/VersaWhiteboard and have currently implemented mobile support. I'm now implementing a multi-page function since the original one didn't have one (the page is currently set to a huge standard size).

**Comment by huzaifahj** [comment]
I actually came across that project and thought mobile and multi-pages are the only thing it lacked. Great work! I'll be keeping up with it and contributing when I have time. Does it need a design overhaul?

**Comment by mntmn** [comment]
While I appreciate your feedback here, this is an issue tracker for Spacedeck. Please take your private discussion to another place.

**Comment by lol7344** [comment]
Yes, you are completely right. However, I would like to note that this issue was opened for a feature request, and we have been talking about that feature ever since. No one cared to respond, and since both me and @huzaifahj had the need of that feature, I actually went on and implemented it myself, sharing the process with him.
I agree this is no longer Spacedeck related, but that's because we were talking about the feature in _general_, not only in Spacedeck.
I assure you if anyone gave us any feedback about it I wouldn't have forked that other project and started working on it.
Also, GitHub does not provide any way to send private messages, and @huzaifahj does not have any contact info on his profile...
Anyway, let's don't start a drama. @huzaifahj  you can find my email on my profile if you'd like to chat.

Have a good day, and good luck with the project! :)
(I'll leave the issue open in case anyone wants to address the feature request)

**Comment by mntmn** [comment]
To move back on topic, I totally agree with this feature request. It was working like this in one Spacedeck version, not sure why it isn't anymore. Will look into it.

**Comment by lol7344** [comment]
Well, if you could make this a feature of Spacedeck it'd be awesome since it's a really good and polished project compared to every other one out there :D

**Comment by mntmn** [comment]
Fixed in 43d21ddb6c438980160fbc607503385b1c3c1d4f, give it a try!

**Comment by huzaifahj** [comment]
Works fine for me now!
