### ISSUE TITLE
Way to annotate large images

### ISSUE THREAD

**Issue by whazlewo** [spacedeck/spacedeck-open#44]
I set a large image as the canvas background, but found that I could not use it effectively for annotation because of (what I assume) is a dynamic background. This feature makes a lot of sense to support an infinite whiteboard. However, is there some way to include the ability to have either a locked canvas, or a locked non-scaled image for shared annotation? 

Glad you guys are keeping this somewhat updated, it has a lot of potential, and I just don't see a lot of similar options out in the wild :-)  Thanks again.

**Comment by mntmn** [comment]
So there is actually a way to lock images, if you click "More" in the right panel, there are lock and unlock buttons.

But it is currently not possible to create new items directly on top of other / locked items, so this has to be solved.

**Comment by mntmn** [comment]
This is fixed now, although it can still be improved.
