### ISSUE TITLE
Space: Moving an element below another element (Z axis) doesn't work reliably

### ISSUE THREAD

**Issue by mntmn** [spacedeck/spacedeck-open#49]
Also, moving an element up in the stacking order is not reliable.

**Comment by huzaifahj** [comment]
[Do you mean like this?](https://imgur.com/a/O6adwCs). Can't select the circle beneath the lines

**Comment by mntmn** [comment]
No, this is a different problem that should also be addressed. What I mean is the functionality of the first 2 buttons under "Align".

**Comment by mntmn** [comment]
Fixed.
