### ISSUE TITLE
Editing Text: space key is not working in copied text elements

### ISSUE THREAD

**Issue by luebbert42** [spacedeck/spacedeck-open#53]
Browser: 
- Firefox for Mac (for Details: https://www.whatismybrowser.com/w/BBZS6RB)

Issue noticed:
- cannot use space key when editing copied text elements

Steps to reproduce:

1. create text element
2. copy text element
3. edit text element and use space key

Demo (short video recording):

- https://www.loom.com/share/b9deb6db81bf412cb6babdcd97eb21e2

Reproducable:

- yes

**Comment by mntmn** [comment]
I'm sorry, cannot reproduce it with Firefox on Linux. Is this still a problem?

**Comment by juliandavidmr** [comment]
This problem was tested on Firefox 82.0.3 (64-bit) (for Mac) and it works. I recommend updating to the latest version of Firefox.
