### ISSUE TITLE
Playing uploaded audio files requires page reload

### ISSUE THREAD

**Issue by fkohrt** [spacedeck/spacedeck-open#54]
Similar to the description in #25, after I upload some media file (e. g. [Siesta](https://freemusicarchive.org/music/Jahzzar/Travellers_Guide/Siesta) or [Bard solo fun](https://freesound.org/people/Akrythael/sounds/334919/)) I get a nice waveform. But if I then click on the play button, the interface changes as if there's something playing, but there's no audible sound. Only after I reload the page I can click the play button and hear the sound. After the page reload, the waveforms appear in a darker blue than before.

Tested with node v10.20.1 and v12.16.3, both on Chromium 80 as well on Firefox 74.

**edit** I noticed a similar behaviour when choosing a background image: only a page reload shows it.

**Comment by mntmn** [comment]
possibly related to #69

**Comment by mntmn** [comment]
This is now fixed. Can you confirm?

**Comment by fkohrt** [comment]
Cool, yes, I can confirm that both audio files and background images work without a page reload!
