### ISSUE TITLE
Docker: Audio conversion issue - ffmpeg

### ISSUE THREAD

**Issue by luigisiricola1997** [spacedeck/spacedeck-open#60]
# Issue:
I tried the dockerized version of spacedeck, but I got an audio conversion issue.
the audio remains as shown in the image below:
![image](https://user-images.githubusercontent.com/28057199/82894438-dea96700-9f52-11ea-9f35-6fbe06adbb40.png)
So I opened the Dockerfile, and I found out this command:
`RUN apk add graphicsmagick ffmpeg-dev ghostscript`

# Solution:
I fixed the issue by replacing `ffmpeg-dev` with `ffmpeg`.

**Comment by fkohrt** [comment]
Oh yeah, shouldn't have replaced `ffmpeg` in b6fd506900c9d0966b8707002bfb6f20300a8efc.
