### ISSUE TITLE
scribble

### ISSUE THREAD

**Issue by Maninarang** [spacedeck/spacedeck-open#7]
when we draw a scribble..it takes couple of second or have to hold the mouse for some time to actualy draw.. how  to reduce that time??

**Comment by Maninarang** [comment]
any sugestion on this please??

**Comment by Maninarang** [comment]
actualy i tried a lot but could find a solution for this.. this is very imp for me.. if you could spare some time..it will be very helpful..
Thanks

**Comment by mntmn** [comment]
Closing because there was no way provided to reproduce the issue.
