### ISSUE TITLE
[Duplicate of issue #41]Cannot create new user - error_Invalid Invite Code.

### ISSUE THREAD

**Issue by marooo9** [spacedeck/spacedeck-open#72]
I keep getting error_Invalid Invite Code. no matter what I put in that field

**Comment by tim-krieger** [comment]
I think this is duplicate to issue #41. You can find the invite code in config/default.json. But you can also define a new one.

**Comment by marooo9** [comment]
Yep it worked - thanks for bringing that up and resolved my issue
