### ISSUE TITLE
Lack of fonts / how do I add new fonts / documentation?

### ISSUE THREAD

**Issue by MishkinBerteig** [spacedeck/spacedeck-open#77]
I tried adding a font to the public/fonts folder and restarting the server, but unfortunately this was not sufficient to get the fonts into the user interface.  I'm okay with being pointed to the right spot in the code to work on this... I'm a (rusty) Nodejs programmer.

**Comment by MishkinBerteig** [comment]
Okay... I seem to have figured it out.  Steps to add fonts:
1. Find the googleapi link for the font, e.g. and add it to styles/type.scss after the "Inter" font that is already there.
2. Add the name of the font to the file public/javascripts/spacedeck_sections.js file on around line 150.
3. From the root of your install, do "gulp styles"
4. Restart your server.

NOTE: the above instructions are super brief and are meant for people who are comfortable with code.
NOTE: one does NOT need to add the font to the public/fonts folder.

I'm not sure if I've missed any spots where the code should be changed, but this seems to work.

**Comment by mntmn** [comment]
Hi, good idea. Lets start adding some documentation. Maybe you can do a PR with the following:

- add a "docs" folder
- Put your second comment in a "adding_fonts.md" markdown file in this folder.

Later we can link to these docs from the README. What do you think?

**Comment by MishkinBerteig** [comment]
I like this... I will work on it and submit a PR.
