### ISSUE TITLE
Implement Eraser Functionality

### ISSUE THREAD

**Issue by mowaiskalam** [spacedeck/spacedeck-open#92]
Hi, This tool is really super cool. I have successfully added the 2 new shapes in it.

My client wants me to implement the Eraser feature, I tried different strategies but no luck. Can anyone guide me how can I add the eraser functionality. I would be very thankful

Thanks

**Comment by mowaiskalam** [comment]
Anyone here to guide me about this @mntmn

**Comment by mntmn** [comment]
Sorry, I can't help you with that directly.
