### ISSUE TITLE
Looking for help: Media Upload not working

### ISSUE THREAD

**Issue by Lukeva** [spacedeck/spacedeck-open#93]
Hello, 
I am having some trouble getting media uploads working. Unfortunately I´m quite new to server administration, but found spacedeck to be a good project to learn with :-)

**Problem:**  When I try to upload a picture into a space it does only show the blue "uploading" box. I get the following log report, making me think this has to do with a faulty configuration on my side. 

**System:** I am using a VPS from Hetzner with Ubuntu 18.08, having spacedeck run in docker with nginx. I am not using a storage box or cdn. I also installes both ffmpeg and imagemagick - also on the system and couldn´t find any similar issue that could help me, which is why I´m writing now and would very much appreciate any help!

Here is the **error log**:
`spacedeck    | [2020-09-07T23:58:22.732Z] [storage] uploading /tmp/sue_logo_foerderung.jpg  to  se8c51dc9-d3a1-4690-9efd-49cc55ec0371/a0a4d8975-71e5-4f9b-a78a-65b407213ca2/sue_logo_foerderung.jpg
spacedeck    | /app/node_modules/config/lib/config.js:181
spacedeck    |     throw new Error('Configuration property "' + property + '" is not defined');
spacedeck    |     ^
spacedeck    |
spacedeck    | Error: Configuration property "storage_cdn" is not defined
spacedeck    |     at Config.get (/app/node_modules/config/lib/config.js:181:11)
spacedeck    |     at /app/helpers/uploader.js:77:30
spacedeck    |     at done (/app/node_modules/mock-aws-s3/lib/mock.js:389:14)
spacedeck    |     at WriteStream.<anonymous> (/app/node_modules/mock-aws-s3/lib/mock.js:409:5)
spacedeck    |     at WriteStream.emit (events.js:203:15)
spacedeck    |     at finishMaybe (_stream_writable.js:646:14)
spacedeck    |     at stream._final (_stream_writable.js:624:5)
spacedeck    |     at WriteStream._final (internal/fs/streams.js:268:3)
spacedeck    |     at callFinal (_stream_writable.js:617:10)
spacedeck    |     at process._tickCallback (internal/process/next_tick.js:63:19)
`
And here you can find the "storage section" from the **config file** - I didn´t really change it, since I also got an error when I commented our the cdn entry:
` "storage_region": "eu-central-1",
  "storage_bucket": "my_spacedeck_bucket",
  "storage_cdn": "/storage",
  "storage_local_path": "./storage",
`
Best
Lukas

**Comment by mntmn** [comment]
Maybe it's loading a different config file? Do you have multiple files in `config/`?

**Comment by Lukeva** [comment]
Thanks for the hint - unfortunately from what I can see, there is only one config file in the folder... :(
If you have a few minutes to take a look yourself, I could send you the SSH-login. I did however find that I skipped two lines in the last log I dumped - don´t know if they might have to do with it - here the complete log for the image upload I tried now: 
```
spacedeck    | [2020-09-09T16:34:05.605Z] [convert] fn: FONA_Logo_gro.jpg local: /tmp/FONA_Logo_gro.jpg mimeType: image/jpeg
spacedeck    | [2020-09-09T16:34:05.629Z] [convert] gm: undefined { width: 1635, height: 652 }
spacedeck    | [2020-09-09T16:34:05.648Z] [storage] uploading /tmp/FONA_Logo_gro.jpg  to  se8c51dc9-d3a1-4690-9efd-49cc55ec0371/a06c5a0a5-f346-4b27-be74-01dd884b0c7c/FONA_Logo_gro.jpg
spacedeck    | /app/node_modules/config/lib/config.js:181
spacedeck    |     throw new Error('Configuration property "' + property + '" is not defined');
spacedeck    |     ^
spacedeck    |
spacedeck    | Error: Configuration property "storage_cdn" is not defined
spacedeck    |     at Config.get (/app/node_modules/config/lib/config.js:181:11)
spacedeck    |     at /app/helpers/uploader.js:77:30
spacedeck    |     at done (/app/node_modules/mock-aws-s3/lib/mock.js:389:14)
spacedeck    |     at WriteStream.<anonymous> (/app/node_modules/mock-aws-s3/lib/mock.js:409:5)
spacedeck    |     at WriteStream.emit (events.js:203:15)
spacedeck    |     at finishMaybe (_stream_writable.js:646:14)
spacedeck    |     at stream._final (_stream_writable.js:624:5)
spacedeck    |     at WriteStream._final (internal/fs/streams.js:268:3)
spacedeck    |     at callFinal (_stream_writable.js:617:10)
spacedeck    |     at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by mntmn** [comment]
I mean, it complains about "storage_cdn" not being defined in the config file. Could you, just for a test, restore the default configuration from the repo? I can also take a quick look if you mail me the ssh data. But it seems like the config file is either not found or there is some error in it.

**Comment by theAkito** [comment]
@Lukeva 

You should only change the parts of `default.json` which are necessary to be changed. If you just delete a value from required key, you will face errors, like these. I think, this issue can be closed.
