### ISSUE TITLE
Space Background Image is broken

### ISSUE THREAD

**Issue by mntmn** [spacedeck/spacedeck-open#95]
When selecting Canvas -> Image and uploading an image file, only a spinning hourglass appears.

After a reload, the background is set. But the feature is non-intuitive because auto-growing the Space also changes the alignment of the background.

Suggestion: If a background image is set, lock the Space size to the exact dimensions of this image.

**Comment by tim-krieger** [comment]
I think this is related to #54?

**Comment by mntmn** [comment]
This is fixed now.
