### ISSUE TITLE
UI size is not scalable

### ISSUE THREAD

**Issue by theAkito** [spacedeck/spacedeck-open#97]
The UI size is way too huge. Currently, one has to use the browser's zoom functionality to reduce the UI's size (currently using 67% zoom). However, it would be much better design to implement a UI scaler natively, which resizes the UI with better results.

**Comment by mntmn** [comment]
The issue topic is ableist. Please change it to something neutral.

**Comment by theAkito** [comment]
What's your personal definition of ableist? There is nothing wrong with this topic.

**Comment by mntmn** [comment]
What I meant is that an accessible UI is not an issue (a bad thing). Why shouldn't the software be for your "grandparents"? The real issue is that _you_ don't require this UI size / prefer a smaller UI size. So just formulate your issues in this way or preferrably a neutral way.
